### ISSUE TITLE
Provide pkl datasets 

### ISSUE THREAD

**Issue by Isminoula** [afshinrahimi/acl2017#1]
Hello,

Truly enjoyed reading your work 👍 
Could you provide the pkl datasets? Perhaps a dropbox link would be good?

Thanks!

**Comment by afshinrahimi** [comment]
Hello Isminoula,

Happy to hear you're also doing research in the same field.
The dataset pkl files are shared [here](https://www.dropbox.com/sh/vofn0awjcjxhwbc/AABHekl2pmFk2Q3qdVO60JTKa?dl=0).

Please do tell me if there was other issues.

Afshin

**Comment by Isminoula** [comment]
Hello Afshin,

Thanks, I was able to download the dataset and run your code, all good!


Have a great day,

Isminoula

**Comment by afshinrahimi** [comment]
nice to hear Isminoula!
